insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('25719','Aargauische Kantonalbank','AKB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('180745','Bank am Bellevue AG','BB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('74453','Bank J. Safra Sarasin AG','SAR','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('556475','Bank J. Safra Sarasin AG','SAR','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('74453','Bank J. Safra Sarasin AG  Basel','SAR','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('556475','Bank J. Safra Sarasin AG  Zweigniederlassung Guernsey','SAR','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('556475','Bank J. Safra Sarasin Ltd','SAR','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('28022','Bank Julius Baer & Co AG  Zurich','SAR','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('135369','Bank Julius Baer & Co Ltd  Guernsey','SAR','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('28022','Bank Julius Baer & Co. AG  Zurich','SAR','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('423004','Bank Sarasin & Cie','JB','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('74453','Bank Sarasin & Cie AG','JB','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('556475','Bank Sarasin & Co. Limited','JB','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('164513','Bank Sarasin (CI) Limited','JB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('63931','Bank Vontobel AG','VON','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('63931','Bank Vontobel AG  Z?rich','VON','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('63931','Bank Vontobel AG  ZALrich','VON','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('63931','Bank Vontobel AG  Zurich','VON','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('419829','Bank Vontobel Cayman','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('26588','Banque Cantonale Vaudoise','BCV','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('190650','BANQUE CANTONALE VAUDOISE','BCV','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('190650','Banque Cantonale Vaudoise (Guernsey Branch)','BCV','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('190650','Banque Cantonale Vaudoise Guernsey  Branch','BCV','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('190650','BANQUE CANTONALE VAUDOISE GUERNSEY BRANCH','BCV','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('360488','Barclays Bank PLC','BVG','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('25839','Basler Kantonalbank','BKB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('408536','BKB Finance Ltd  Guernsey','BKB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('141097','BNP Paribas Arbitrage Issuance B.V','BNP','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('141097','BNP Paribas Arbitrage Issuance B.V.','BNP','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('141097','BNP Paribas Arbitrage Issuance BV','BNP','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('273832','Citigroup Funding Inc.','BNP','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('130800','Clariden Leu AG','BNP','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('186183','Clariden Leu Ltd  Nassau Branch','BNP','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('186183','Clariden Leu Ltd.  Nassau Branch  Bahamas','BNP','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('130800','Clariden Leu Ltd.  Zurich','BNP','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('299352','Commerzbank AG','BNP','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('49406','Corner Bank Ltd.','CORNER','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('359727','Cosmo Pharmaceuticals S.p.A.','CORNER','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('567569','Credit Suisse','CORNER','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('602340','Credit Suisse  AG  London Branch','CS','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('567569','Credit Suisse  Zurich','CSLB','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('118495','Credit Suisse AG  Guernsey Branch','CS','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('602340','Credit Suisse AG  London Branch','CS','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('314667','Credit Suisse AG  Nassau Branch','CS','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('314667','Credit Suisse AG  Nassau Branch  Bahamas','CS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('567569','Credit Suisse AG  Zurich','CS','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('97970','Credit Suisse International','CS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('299606','Deutsche Bank AG','DB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('56224','Deutsche Bank AG','DB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('361630','Deutsche Bank AG','DB','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('361630','Deutsche Bank AG London','DB','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('350057','DWS GO SA','DB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('300220','DZ BANK AG (Deutsche Zentral-Genossenschaftsbank)','DB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('625235','EFG Bank','DB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('410499','EFG Financial Products (Guernsey) Limited','EFG','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('406691','EFG Financial Products AG','EFG','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('410499','EFG Financial Products AG','EFG','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('597190','EFG Financial Products AG  Guernsey Branch','EFG','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('303585','EFG International AG  ZALrich','EFG','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('410499','EFG International Finance (Gernsey) Limited','EFG','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('410499','EFG International Finance (Guernsey) Limited','EFG','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('410499','EFG International Finance (Guernsey) Ltd','EFG','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('410499','EFG International Finance Guernsey Ltd','EFG','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('164654','Exane Finance','EFG','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('748120','Goldman  Sachs & Co. Wertpapier GmbH Frankfurt','EFG','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('411209','Goldman Sachs Bank AG','EFG','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('738468','Goldman Sachs Finance Corp International Ltd','GSFCI','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('562832','Goldman Sachs International','GSI','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('391856','Goldman Sachs International','GSI','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('748120','Goldman Sachs Wertpapier','GSW','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('41211','HSBC Trinkaus & Burkhardt AG','NHB','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('74453','J. Safra Sarasin AG','NHB','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('556475','J. Safra Sarasin Ltd','NHB','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('592599','J.P. Morgan Bank Luxembourg S.A.','NHB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('163512','J.P. Morgan International Derivatives Ltd','NHB','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('381915','J.P.Morgan Structured Products B.V.','NHB','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('406691','Leonteq Securities AG','LEONGUE','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('597190','Leonteq Securities AG  Guernsey Branch','LEONGUE','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('406691','Leonteq Securities AG  Zurich','LEONGUE','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('597190','Leonteq Securities AG Guernsey Branch','LEONGUE','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('519503','Macquarie Structured Products (Europe) GmbH','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('513144','Macquarie Structured Products (Europe) GmbH','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('610990','Merrill Lynch B.V','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('62222','Merrill Lynch Capital Markets AG','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('243619','Merrill Lynch International & Co C.V.','KBLU','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('243619','Merrill Lynch International & Co CV','KBLU','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('16906','Merrill Lynch SA','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('83400','Migros Bank','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('861132','Morgan Stanley','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('408308','Morgan Stanley & Co. International Plc','KBLU','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('132636','Morgan Stanley B.V.','KBLU','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('132636','Morgan Stanley BV','MS','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('711153','Morgan Stanley Finance LLC','MORGFI','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('553937','Neue Helvetische Bank AG','RBSPLC','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('658903','Notenstein Finance (Guernsey) Limited','RBSPLC','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('214225','Notenstein La Roche Private Bank Ltd.','RBSPLC','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('214225','Notenstein Private Bank Ltd.','RBSPLC','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('296916','Rabobank International','RBSPLC','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('30207','Rabobank International','RBSPLC','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('30207','Rabobank Nederland NV','RBSPLC','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('708630','Raiffeisen Switzerland','RBSPLC','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('725842','Raiffeisen Switzerland B.V.','RAIFFNL','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('367219','RBS Bank plc','BKSVR','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('256590','RBS NV','BKSVR','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('367219','RBS plc','BKSVR','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('602519','Royal Bank of Canada','BKSVR','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('670909','Royal Bank of Canada','BKSVR','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('367212','Royal Bank of Canada  London Branch','BKSVR','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('607359','SG Issuer','SGISS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('499025','SG Option Europe','SGISS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('84400','SG Option Europe','SGISS','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('499025','SGA SociA©tA© GA©nA©rale Acceptance','SGISS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('499025','SGA SociA©tA© GA©nA©rale Acceptance NV','SGISS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('256590','The Royal Bank of Scotland NV','GLEFR','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('391161','The Royal Bank of Scotland NV','GLEFR','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('409585','The Royal Bank of Scotland NV London','GLEFR','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('367219','The Royal Bank of Scotland plc','GLEFR','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('1704','UBS AG','UBS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6108','UBS AG   London Branch','UBS','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('1704','UBS AG   Zurich','UBS','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6518','UBS AG  Jersey','UBS','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6518','UBS AG  Jersey Branch','UBS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6108','UBS AG  Jersey Branch','UBS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6108','UBS AG  London','UBS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6108','UBS AG  London Branch','UBS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('1704','UBS AG  London Branch','UBS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('1704','UBS AG  Zurich','UBS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6518','UBS AG Jersey Branch','UBS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('6108','UBS AG London Branch','UBS','now()','10000','now()','10000');*/
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('1704','UBS AG Zurich','UBS','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('11554','UniCredit Bank AG','UBS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('25996','Valartis Bank AG','UBS','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('285328','Vontobel Financial Products GmbH','VON','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('285328','Vontobel Financial Products GmbH  Frankfurt a. M','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('285328','Vontobel Financial Products GmbH  Frankfurt a. M.','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('285328','Vontobel Financial Products GmbH  Frankfurt am Main','VON','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('416131','Vontobel Financial Products Ltd','VON','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('416131','Vontobel Financial Products Ltd  DIFC Dubai','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('416131','Vontobel Financial Products Ltd.  DIFC Dubai','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('416131','Vontobel Financial Products Ltd.; Dubai','VON','now()','10000','now()','10000');*/
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('26338','Z?rcher Kantonalbank','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('103223','Z?rcher Kantonalbank Finance (Guernsey) Ltd','VON','now()','10000','now()','10000');
/*insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('26338','ZALrcher Kantonalbank','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('103223','ZALrcher Kantonalbank Finance (Guernsey) Ltd','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('26338','Zuercher Kantonalbank','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('103223','Zuercher Kantonalbank','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('103223','Zuercher Kantonalbank Finance (Guernsey)','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('103223','Zuercher Kantonalbank Finance (Guernsey) Ltd','VON','now()','10000','now()','10000');
insert into rules.tkpartykey_issuercode_rule(tkPartyKey, partyName, issuerCode, created, createdBy, lastModified, lastModifiedBy)values('26338','Zuercher Kantonalbank Finance (Guernsey) Ltd.','VON','now()','10000','now()','10000');*/
